steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_APP_NAME}:$COMMIT_SHA', '.']

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_APP_NAME}:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_APP_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_APP_NAME}:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--service-account'
      - '${_APP_NAME}-sa@$PROJECT_ID.iam.gserviceaccount.com'

substitutions:
  _APP_NAME: marketing-automation
  _REGION: us-central1

images:
  - 'gcr.io/$PROJECT_ID/${_APP_NAME}:$COMMIT_SHA'