name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Google Cloud
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Set up authentication for Google Cloud
      # Option 1: Using Workload Identity Federation (recommended)
      - name: Google Auth
        id: auth
        if: "${{ env.USE_WORKLOAD_IDENTITY == 'true' }}"
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      
      # Option 2: Using Service Account Key
      - name: Google Auth with Key
        id: auth-key
        if: "${{ env.USE_WORKLOAD_IDENTITY != 'true' }}"
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Authorize Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_PROJECT_ID }}-docker.pkg.dev
      
      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/marketing-automation-repo/marketing-automation:latest
            us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/marketing-automation-repo/marketing-automation:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Store OpenAI API Key in Secret Manager
        run: |
          echo "${{ secrets.OPENAI_API_KEY }}" | gcloud secrets create openai-api-key --replication-policy="automatic" --data-file=- || \
          echo "${{ secrets.OPENAI_API_KEY }}" | gcloud secrets versions add openai-api-key --data-file=-
      
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: marketing-automation
          region: us-central1
          image: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/marketing-automation-repo/marketing-automation:${{ github.sha }}
          env_vars: |
            NODE_ENV=production
          secrets: |
            OPENAI_API_KEY=openai-api-key:latest
      
      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}